### ISSUE TITLE
advantages compared to the plan9 acme

### ISSUE THREAD

**Issue by rythmkraze** [rjkroege/edwood#266]
What additional benefits does edwood provide compared to acme?
Or Why use edwood over acme on unix?

**Comment by fhs** [comment]
The only benefit I can think of is that Edwood uses JSON for dump file and can save multi-line tags. As a user, currently, there is more disadvantage to using Edwood because of how unstable it is compared to acme.

Being written in Go, the real benefit of Edwood is for developers who wants to hack on it and experiment with adding new features.

**Comment by rythmkraze** [comment]
Got it. Thanks for the explanation @fhs
