### ISSUE TITLE
win locks

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#44]
in Acme, `win` would regularly lock up in some fashion. Like 1/week.

In Edwood, `win` also regularly locks up. It just does it a lot more frequently: like every few commands.

**Comment by paul-lalonde** [comment]
I think unicode handling can do this - leaving win craving more input, and blocking.  There's a few places where rune vs byte counts can easily get confused, leading to an fsys unsatisfied read loop.  That might be happening in the original.  The fix to #43 may help stabilize this - I know there was a problem there, and it would only cause a crash when the buffer was at RBUFSIZE or so, but would give bad/miscounted reads otherwise.

**Comment by rjkroege** [comment]
It seems to reliably get confused when there is typing at the shell already and one middle-drags to send the selection to the end of the in-progress command line.

**Comment by paul-lalonde** [comment]
Ok, I think my patch from earlier today fixes this.  At least I can't repro here this morning with my new change, though I haven't tried reproducing it without that fix ;-)

**Comment by rjkroege** [comment]
I've had win lock since. But it's much better. Probably good enough for .1

**Comment by rjkroege** [comment]
I'm becoming less happy with how well this work. Editing the `win` window seems to reliably lock `win` up. Are we seeing a problem from simultaneous mutators?

**Comment by rjkroege** [comment]
Appears to be fixed with the addition of `frame.Frame` thread safety in b8089af74350e8a79148941634b7cf605dfb841c.
